### ISSUE TITLE
Why is Node 0.10 required?

### ISSUE THREAD

**Issue by MattiSG** [mateogianolio/node-pip#2]
The reliance on an old (0.10) version of Node is a bit of a bummer. Why is it required to use that version rather than 0.12? What is the probability of compatibility with Node 4.0?

**Comment by mateogianolio** [comment]
It's because building (node-python](https://github.com/chrisdickinson/node-python) requires old v8 bindings.

**Comment by MattiSG** [comment]
Ok, thanks! Do you know of any alternative project to `node-python`, which hasn't been updated in 4 years?
