### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by dbkaplun** [mateogianolio/node-pip#3]
Can you give a high-level overview of how this NodeJS code runs Python? Does it implement a Python interpreter? Does it serialize in CPython and deserialize in Node? An explanation would be very helpful to make me confident in using this in my own code.

**Comment by mateogianolio** [comment]
It imports python modules with the standard ```PyImport_Import```and then wraps it into a v8 object using ```node::ObjectWrap```.

Check [electronifie/node-python](https://github.com/electronifie/node-python) under "Current status" for working type conversions.
